name: voicetrainng
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # HTTP, íŒŒì¼ ì„ íƒ
  http: ^1.2.0
  file_picker: ^8.0.0
  http_parser: ^4.0.2

  # ğŸ™ï¸ ë…¹ìŒ + ì¬ìƒ ì¶”ê°€
  record: ^5.0.4
  audioplayers: ^5.2.0

  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.ttf
        - asset: assets/fonts/NotoSansKR-Medium.ttf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.ttf
          weight: 700




